---
title: Customize
---

## Edit and add your pages

Edit the qmd or md files in the `content` folder. qmd files can include code (R, Python, Julia) and lots of Quarto markdown bells and whistles (like call-outs, cross-references, auto-citations and much more).

Each page should start with

    ---
    title: your title
    ---

and the first header will be the 2nd level, so `##`. Note, there are situations where you leave off

    ---
    title: your title
    ---

and start the qmd file with a level header `#`, but if using the default title yaml (in the `---` fence) is a good habit since it makes it easy for Quarto convert your qmd file to other formats (like into a presentation).

## Add your pages the project

-   Add the files to `_quarto.yml`

---
title: "Methods_Cameras"
editor: visual
---

### Cameras

One full view (standard) digital video camera and one narrow view (zoomed) digital video camera mounted side by side were operated together on most counting passes. The "standard" camera is generally at maximum wide angle to keep the entire group of belugas in view. This wide angle video is used to count the total number of whales surfacing during the video pass. The second "zoomed" camera is kept at maximum optical zoom (10×) and its video was used to determine correction factors for missed whales (Hobbs et al. 2015). Once recording is started, the zoom setting for each camera was set and left unchanged throughout a counting pass so that magnification of the video was consistent.

In 2021, a "standard" camera (Sony HXR-NX5U HD with 1920 × 1080 pixel resolution) was paired with a "zoomed" camera (Panasonic HC-X1 with 3840 × 2160 (4K) pixel resolution but set to the same resolution as the Sony camera). This was the same camera set up used during the 2018 abundance survey, with the Panasonic replacing one of the paired Sony cameras used during the 2016 survey. Plans at the time had been to test the 4K resolution against the older cameras but this did not occur in 2018 or 2021 as other experiments such as distance sampling became a priority.

In 2022, smaller 4K resolution video cameras were introduced to improve the quality of video data collection. The Sony FDR-AX700 video handycams (3840 × 2160 pixel resolution) replaced the larger video cameras allowing for easier handling and positioning for capturing video. A new aluminum based camera mounting system was created with tripod mounts for the two video cameras (Fig 5a). The mounting system had adjustable brackets which allowed for side by side (Fig. 5b) or stacking (Fig. 5c) of cameras so alignment could be customized based on camera size. A series of video passes were collected to compare the 1080p resolution of the Sony HXR-NX5U used in 2021 to 4K resolution of the new Sony FDR-AX700 cameras used in 2022 (Fig. 5c). Preliminary review of comparison video shows the 4K resolution increases edge definition and clarity of whale images.

After the field season, each video counting pass was reviewed for quality and rated as excellent, good, fair, poor, or unacceptable. Video passes rated excellent and good were analyzed using a computer-aided system called "Beluga Dots" (introduced in 2004). Using Beluga Dots (Fig. 6), analysts counted and cataloged the individual whale images found in the survey video, tracked the images across the computer screen, and measured image size and color. Data were stored in a text file and exported for use in calculating the annual abundance estimate. Images from the zoomed camera were examined for whale surfacings that could not be seen in the standard video, either due to a partial surfacing, small size, or cryptic body coloration within the respective groups. The annual abundance estimate is based on estimates of the size of detected groups, using Bayesian methods to account for: 1) availability bias due to diving behavior; 2) proximity bias due to whales concealed by other whales in the video data; 3) perception bias due to whales not detected because of small image size in the standard video; and 4) individual observer bias in visual observer data (see Boyd et al. (2019) for a complete description of methods).
